#!/bin/sh /etc/rc.common

START=88

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
	/usr/bin/fmlink_drone &
	sleep 5
	insmod /lib/modules/3.3.8/ath_udc.ko
	insmod /lib/modules/3.3.8/g_ether.ko
}

stop() {
	killall -9 fmlink_drone
}

