package com.fimi.app.x8s.enums;

public enum X8AiFlyMenuEnum {
    ALL_ITEMS,
    AI_TAKE_OFF,
    AI_LANDING,
    AI_RETURN,
    AI_FOLLOW_CONFIRM,
    AI_POINT2POINT_CONFIRM,
    AI_SURROUNDPOINT_CONFIRM,
    AI_LINE_CONFIRM,
    AI_AUTO_PHOTO_CONFIRM,
    AI_TTIPOD,
    AI_AERIALPHOTOGRAPH,
    AI_FIXEDWING,
    AI_HEADINGLOCK,
    AI_SCREW,
    AI_SAR,
    AI_FLY_GRAVITATION
}
