#!/bin/sh

# Copyright (C) 2006-2010 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

mount_no_rootfs_data() {
    mtd unlock rootfs
    mount -o remount,rw /dev/root /
}

check_for_rootfs_data() {
    check_skip || {
	grep -qs rootfs_data /proc/mtd || grep -qs ubi_rootfs_data /sys/class/ubi/ubi0/ubi0_1/name || grep -qs rootfs_data /sys/block/mmcblk0/mmcblk0p*/uevent || {
	    mount_no_rootfs_data && pi_mount_skip_next=true
	}
    }
}

boot_hook_add preinit_mount_root check_for_rootfs_data

