#!/bin/sh
# Copyright (C) 2006-2010 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

find_mount_jffs2() {
    mkdir -p /tmp/overlay
    mount "$(find_mtd_part rootfs_data)" /tmp/overlay -t jffs2
    mtd -qq unlock rootfs_data
}

jffs2_not_mounted() {
    if [ "$pi_jffs2_mount_success" != "true" ]; then
	return 0
    else
	return 1
    fi
}

do_mount_jffs2() {
    # skip jffs2 mounting even if it's there if we have volume named
    # ubi_rootfs_data
    check_skip && return
    grep -wqs rootfs_data /proc/mtd || return 1

    find_mount_jffs2 && pi_jffs2_mount_success=true
}

boot_hook_add preinit_mount_root do_mount_jffs2

